/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSaudasRouteImport } from './routes/_app.saudas'
import { Route as AppItemsRouteImport } from './routes/_app.items'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppBillsRouteImport } from './routes/_app.bills'
import { Route as AppAnalysisRouteImport } from './routes/_app.analysis'
import { Route as ApiPublicHooksSyncSheetsRouteImport } from './routes/api/public/hooks/sync-sheets'
import { Route as ApiPublicHooksCleanupSaudasRouteImport } from './routes/api/public/hooks/cleanup-saudas'
import { Route as ApiPublicHooksCleanupBillsRouteImport } from './routes/api/public/hooks/cleanup-bills'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSaudasRoute = AppSaudasRouteImport.update({
  id: '/saudas',
  path: '/saudas',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsRoute = AppItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalysisRoute = AppAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksSyncSheetsRoute =
  ApiPublicHooksSyncSheetsRouteImport.update({
    id: '/api/public/hooks/sync-sheets',
    path: '/api/public/hooks/sync-sheets',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCleanupSaudasRoute =
  ApiPublicHooksCleanupSaudasRouteImport.update({
    id: '/api/public/hooks/cleanup-saudas',
    path: '/api/public/hooks/cleanup-saudas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCleanupBillsRoute =
  ApiPublicHooksCleanupBillsRouteImport.update({
    id: '/api/public/hooks/cleanup-bills',
    path: '/api/public/hooks/cleanup-bills',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/analysis': typeof AppAnalysisRoute
  '/bills': typeof AppBillsRoute
  '/history': typeof AppHistoryRoute
  '/items': typeof AppItemsRoute
  '/saudas': typeof AppSaudasRoute
  '/api/public/hooks/cleanup-bills': typeof ApiPublicHooksCleanupBillsRoute
  '/api/public/hooks/cleanup-saudas': typeof ApiPublicHooksCleanupSaudasRoute
  '/api/public/hooks/sync-sheets': typeof ApiPublicHooksSyncSheetsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/analysis': typeof AppAnalysisRoute
  '/bills': typeof AppBillsRoute
  '/history': typeof AppHistoryRoute
  '/items': typeof AppItemsRoute
  '/saudas': typeof AppSaudasRoute
  '/': typeof AppIndexRoute
  '/api/public/hooks/cleanup-bills': typeof ApiPublicHooksCleanupBillsRoute
  '/api/public/hooks/cleanup-saudas': typeof ApiPublicHooksCleanupSaudasRoute
  '/api/public/hooks/sync-sheets': typeof ApiPublicHooksSyncSheetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/analysis': typeof AppAnalysisRoute
  '/_app/bills': typeof AppBillsRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/items': typeof AppItemsRoute
  '/_app/saudas': typeof AppSaudasRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/hooks/cleanup-bills': typeof ApiPublicHooksCleanupBillsRoute
  '/api/public/hooks/cleanup-saudas': typeof ApiPublicHooksCleanupSaudasRoute
  '/api/public/hooks/sync-sheets': typeof ApiPublicHooksSyncSheetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analysis'
    | '/bills'
    | '/history'
    | '/items'
    | '/saudas'
    | '/api/public/hooks/cleanup-bills'
    | '/api/public/hooks/cleanup-saudas'
    | '/api/public/hooks/sync-sheets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/analysis'
    | '/bills'
    | '/history'
    | '/items'
    | '/saudas'
    | '/'
    | '/api/public/hooks/cleanup-bills'
    | '/api/public/hooks/cleanup-saudas'
    | '/api/public/hooks/sync-sheets'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/analysis'
    | '/_app/bills'
    | '/_app/history'
    | '/_app/items'
    | '/_app/saudas'
    | '/_app/'
    | '/api/public/hooks/cleanup-bills'
    | '/api/public/hooks/cleanup-saudas'
    | '/api/public/hooks/sync-sheets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksCleanupBillsRoute: typeof ApiPublicHooksCleanupBillsRoute
  ApiPublicHooksCleanupSaudasRoute: typeof ApiPublicHooksCleanupSaudasRoute
  ApiPublicHooksSyncSheetsRoute: typeof ApiPublicHooksSyncSheetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saudas': {
      id: '/_app/saudas'
      path: '/saudas'
      fullPath: '/saudas'
      preLoaderRoute: typeof AppSaudasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/items': {
      id: '/_app/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AppItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills': {
      id: '/_app/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analysis': {
      id: '/_app/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AppAnalysisRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/sync-sheets': {
      id: '/api/public/hooks/sync-sheets'
      path: '/api/public/hooks/sync-sheets'
      fullPath: '/api/public/hooks/sync-sheets'
      preLoaderRoute: typeof ApiPublicHooksSyncSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-saudas': {
      id: '/api/public/hooks/cleanup-saudas'
      path: '/api/public/hooks/cleanup-saudas'
      fullPath: '/api/public/hooks/cleanup-saudas'
      preLoaderRoute: typeof ApiPublicHooksCleanupSaudasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-bills': {
      id: '/api/public/hooks/cleanup-bills'
      path: '/api/public/hooks/cleanup-bills'
      fullPath: '/api/public/hooks/cleanup-bills'
      preLoaderRoute: typeof ApiPublicHooksCleanupBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAnalysisRoute: typeof AppAnalysisRoute
  AppBillsRoute: typeof AppBillsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppItemsRoute: typeof AppItemsRoute
  AppSaudasRoute: typeof AppSaudasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalysisRoute: AppAnalysisRoute,
  AppBillsRoute: AppBillsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppItemsRoute: AppItemsRoute,
  AppSaudasRoute: AppSaudasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksCleanupBillsRoute: ApiPublicHooksCleanupBillsRoute,
  ApiPublicHooksCleanupSaudasRoute: ApiPublicHooksCleanupSaudasRoute,
  ApiPublicHooksSyncSheetsRoute: ApiPublicHooksSyncSheetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
